import { type Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts frontend/types`.

export type Facility = Models.Document & {
    name: string;
    district: string;
    address: string;
    contactPhone: string;
    contact_phone: string | null;
    created_at: string;
    updated_at: string;
}

export type Patients = Models.Document & {
    full_name: string;
    sex: string;
    date_of_birth: string;
    mother_name: string | null;
    father_name: string | null;
    district: string;
    town_village: string | null;
    address: string;
    contact_phone: string | null;
    health_worker_id: string | null;
    health_worker_name: string | null;
    health_worker_phone: string | null;
    health_worker_address: string | null;
    facility_id: string;
    created_at: string;
    updated_at: string;
    patient_profile_id: string | null;
    profile_verification_status: string | null;
    guardian_profile_id: string | null;
    profile_access_permissions: string[] | null;
    profile_notification_preferences: string | null;
}

export type Vaccines = Models.Document & {
    name: string;
    description: string | null;
    vaccine_code: string;
    sequence_number: number | null;
    vaccine_series: string | null;
    standard_schedule_age: string | null;
    created_at: string;
    updated_at: string;
    is_supplementary: boolean;
    is_active: boolean;
}

export type ImmunizationRecords = Models.Document & {
    patient_id: string;
    vaccine_id: string;
    administered_date: string;
    administered_by_user_id: string;
    facility_id: string;
    batch_number: string;
    health_officer: string | null;
    return_date: string | null;
    is_standard_schedule: boolean;
    schedule_status: string | null;
    notes: string | null;
    created_at: string;
    updated_at: string;
    administered_by_profile_id: string | null;
    administered_by_employee_id: string | null;
    administered_by_professional_title: string | null;
    administered_by_license_number: string | null;
    administered_by_specializations: string[] | null;
    supervisor_profile_id: string | null;
    quality_assurance_verified: boolean;
    verification_timestamp: string | null;
}

export type Notifications = Models.Document & {
    patient_id: string;
    vaccine_id: string;
    due_date: string;
    facility_id: string;
    message: string | null;
    sent_at: string | null;
    viewed_at: string | null;
    created_at: string;
    updated_at: string;
    recipient_profile_id: string | null;
    recipient_profile_type: string | null;
    notification_channels: string[] | null;
    personalization_data: string | null;
    guardian_notification: boolean;
    guardian_profile_id: string | null;
    delivery_preferences: string | null;
    language_preference: string;
    status: string;
    priority: string;
}

export type VaccineSchedules = Models.Document & {
    name: string;
    country: string;
    description: string | null;
    is_active: boolean;
    version: string;
    effective_date: string | null;
    created_by: string | null;
    created_at: string;
    updated_at: string;
}

export type VaccineScheduleItems = Models.Document & {
    schedule_id: string;
    vaccine_id: string;
    recommended_age: string;
    sequence_in_schedule: number;
    minimum_age: string | null;
    maximum_age: string | null;
    interval_from_previous: string | null;
    is_mandatory: boolean;
    notes: string | null;
    created_at: string;
    updated_at: string;
}

export type SupplementaryImmunizations = Models.Document & {
    name: string;
    description: string | null;
    start_date: string;
    end_date: string;
    facility_id: string | null;
    vaccine_id: string;
    target_population: string | null;
    campaign_type: string;
    target_age_min: string | null;
    target_age_max: string | null;
    target_districts: string[] | null;
    status: string;
    created_by: string | null;
    created_at: string;
    updated_at: string;
    created_by_profile_id: string | null;
    created_by_employee_id: string | null;
    created_by_professional_title: string | null;
    campaign_coordinators: string[] | null;
    approval_required: boolean;
    approved_by_profile_id: string | null;
    approval_timestamp: string | null;
}

export type PatientProfiles = Models.Document & {
    user_id: string;
    patient_id: string;
    profile_status: string;
    verification_status: string;
    verification_method: string | null;
    guardian_user_id: string | null;
    access_permissions: string[];
    notification_preferences: string | null;
    emergency_contact: string | null;
    facility_id: string;
    created_at: string;
    updated_at: string;
}

export type EmployeeProfiles = Models.Document & {
    user_id: string;
    employee_id: string;
    employee_type: string;
    professional_title: string | null;
    license_number: string | null;
    license_expiry_date: string | null;
    specializations: string[] | null;
    primary_facility_id: string;
    assigned_facilities: string[] | null;
    department: string | null;
    supervisor_user_id: string | null;
    employment_status: string;
    hire_date: string | null;
    work_schedule: string | null;
    contact_information: string | null;
    emergency_contact: string | null;
    training_records: string | null;
    performance_metrics: string | null;
    created_at: string;
    updated_at: string;
}

export type AdminProfiles = Models.Document & {
    user_id: string;
    admin_level: string;
    system_permissions: string[];
    facility_access_scope: string;
    assigned_facilities: string[] | null;
    security_clearance: string;
    mfa_enabled: boolean;
    last_security_review: string | null;
    audit_log_access: boolean;
    system_config_access: boolean;
    user_management_scope: string;
    backup_admin_user_id: string | null;
    admin_notes: string | null;
    created_at: string;
    updated_at: string;
}

export type AccessAuditLog = Models.Document & {
    user_id: string;
    user_profile_id: string | null;
    user_profile_type: string | null;
    action_type: string;
    resource_type: string;
    resource_id: string | null;
    facility_context: string | null;
    session_context: string | null;
    ip_address: string | null;
    user_agent: string | null;
    success: boolean;
    error_message: string | null;
    additional_data: string | null;
    timestamp: string;
    created_at: string;
}

export type AuditCollections = Models.Document & {
}

export type RoleChangeLog = Models.Document & {
    target_user_id: string;
    target_profile_id: string | null;
    target_profile_type: string | null;
    assigned_by_user_id: string;
    assigned_by_profile_id: string | null;
    assigned_by_profile_type: string | null;
    role_change_type: string;
    previous_roles: string[] | null;
    new_roles: string[];
    previous_teams: string[] | null;
    new_teams: string[] | null;
    facility_context: string | null;
    reason: string | null;
    approval_required: boolean;
    approved_by_user_id: string | null;
    approval_timestamp: string | null;
    effective_date: string;
    expiry_date: string | null;
    status: string;
    created_at: string;
    updated_at: string;
}

export type ProfileVerificationWorkflow = Models.Document & {
    profile_id: string;
    profile_type: string;
    user_id: string;
    verification_type: string;
    verification_method: string;
    status: string;
    initiated_by_user_id: string;
    assigned_to_user_id: string | null;
    facility_id: string;
    verification_data: string | null;
    documents_required: string[] | null;
    documents_submitted: string[] | null;
    verification_notes: string | null;
    rejection_reason: string | null;
    priority: string;
    due_date: string | null;
    completed_at: string | null;
    completed_by_user_id: string | null;
    workflow_steps: string | null;
    created_at: string;
    updated_at: string;
}

export type SyncCollections = Models.Document & {
}

export type Facilities = Models.Document & {
    name: string;
    district: string;
    address: string;
    contact_phone: string | null;
    created_at: string;
    updated_at: string;
}

export type EmployeeProfiles = Models.Document & {
    user_id: string;
    employee_id: string;
    employee_type: string;
    professional_title: string;
    license_number: string | null;
    license_expiry_date: string | null;
    specializations: string[] | null;
    primary_facility_id: string;
    assigned_facilities: string[] | null;
    department: string | null;
    employment_status: string;
    hire_date: string | null;
    contact_information: string | null;
    work_schedule: string | null;
    created_at: string;
    updated_at: string;
}

export type PatientProfiles = Models.Document & {
    user_id: string;
    patient_id: string | null;
    profile_status: string;
    verification_status: string;
    verification_method: string | null;
    access_permissions: string[] | null;
    notification_preferences: string | null;
    emergency_contact: string | null;
    facility_id: string;
    created_at: string;
    updated_at: string;
}

export type ImmunizationRecords = Models.Document & {
    patient_id: string;
    vaccine_id: string;
    facility_id: string;
    administered_by: string;
    administration_date: string;
    batch_number: string | null;
    expiry_date: string | null;
    site_of_administration: string | null;
    dose_number: number | null;
    notes: string | null;
    adverse_reactions: string | null;
    created_at: string;
    updated_at: string;
}
